name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on server
        run: |
          cd /home/githubrunner/Flasharb

          git pull origin main

          docker compose down
          docker compose up -d --build